"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 2.1.
"""

import os
import pymysql
from datetime import timedelta
pymysql.install_as_MySQLdb()

# --------------------
# BASE DIRECTORIES
# --------------------
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#Le chemin pour les export automatique
EXPORT_ROOT = os.path.join(BASE_DIR, 'media', 'exports')

# --------------------
# SECURITY
# --------------------
SECRET_KEY = 'exhlfdat&vfum(-34*c2uroi(($ww(yo$9pv98=e6p^gl(-eoj'
DEBUG = True
ALLOWED_HOSTS = []

# --------------------
# INSTALLED APPS
# --------------------
INSTALLED_APPS = [
    'blog.apps.BlogConfig',
    'users.apps.UsersConfig',
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'rest_framework_simplejwt',
    'ckeditor',  # IMPORTANT : Ajout de CKEditor (SANS ckeditor_uploader)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_apscheduler',
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------
# MIDDLEWARE
# --------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------
# URLS & WSGI
# --------------------
ROOT_URLCONF = 'django_project.urls'
WSGI_APPLICATION = 'django_project.wsgi.application'

# --------------------
# TEMPLATES
# --------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.context_processors.can_add_article',
            ],
        },
    },
]

# --------------------
# DATABASE (SQLite)
# --------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        "OPTIONS": {
            "timeout": 20,  # wait up to 20 seconds before failing
        },
    }
}

# YOU CAN ACTIVATE THIS CODE IF YOU WANT TO USE MariaDB 11 INSTEAD OF SQLITE 
# --------------------
# DATABASE (MariaDB 11 - Optional)
# --------------------
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'your_database_name',
        'USER': 'your_username',
        'PASSWORD': 'your_password',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}
"""

# --------------------
# PASSWORD VALIDATORS
# --------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --------------------
# INTERNATIONALIZATION
# --------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# --------------------
# STATIC FILES
# --------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'blog/static'),
]

# --------------------
# MEDIA FILES
# --------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --------------------
# CRISPY FORMS
# --------------------
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# --------------------
# AUTH REDIRECTS
# --------------------
LOGIN_REDIRECT_URL = 'blog-home'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'

# --------------------
# REST FRAMEWORK CONFIG
# --------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}
# --------------------
# CKEDITOR CONFIGURATION COMPLÈTE (AVEC TOUS LES OUTILS)
# --------------------
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'],
            ['Font', 'FontSize'],  # Contrôles de police
            ['TextColor', 'BGColor'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['Image', 'Table', 'HorizontalRule', 'SpecialChar'],
            ['RemoveFormat', 'Source']
        ],
        'height': 300,
        'width': '100%',
        'removePlugins': '',  # Permet les images si vous le souhaitez
        'allowedContent': True,  # Permet le HTML
        
        # Configuration des polices
        'font_names': 'Arial/Arial, Helvetica, sans-serif;'
                      'Calibri/Calibri, sans-serif;'
                      'Comic Sans MS/Comic Sans MS, cursive;'
                      'Courier New/Courier New, Courier, monospace;'
                      'Georgia/Georgia, serif;'
                      'Lucida Sans Unicode/Lucida Sans Unicode, Lucida Grande, sans-serif;'
                      'Tahoma/Tahoma, Geneva, sans-serif;'
                      'Times New Roman/Times New Roman, Times, serif;'
                      'Trebuchet MS/Trebuchet MS, Helvetica, sans-serif;'
                      'Verdana/Verdana, Geneva, sans-serif;'
                      'Roboto/Roboto, sans-serif;'
                      'Open Sans/Open Sans, sans-serif;'
                      'Montserrat/Montserrat, sans-serif;'
                      'Poppins/Poppins, sans-serif;'
                      'Source Sans Pro/Source Sans Pro, sans-serif;',
        
        'fontSize_sizes': '8/8px;9/9px;10/10px;11/11px;12/12px;14/14px;16/16px;18/18px;20/20px;22/22px;24/24px;26/26px;28/28px;36/36px;48/48px;72/72px',
        
        # Options supplémentaires
        'extraPlugins': 'justify,colorbutton,font',  # Ajoute le plugin justify et font
        'format_tags': 'p;h1;h2;h3;h4;h5;h6;pre;address;div',  # Formats disponibles
    },
}