# Generated by Django 5.2.7 on 2025-10-30 19:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_category_options_alter_comment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Knowledge Article', 'verbose_name_plural': 'Knowledge Articles'},
        ),
        migrations.AlterModelOptions(
            name='posthistory',
            options={'ordering': ['-modified_date'], 'verbose_name_plural': 'Article History'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='usefulvote',
            options={'verbose_name': 'Useful Vote', 'verbose_name_plural': 'Useful Votes'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_solution',
            field=models.BooleanField(default=False, verbose_name='Mark as Solution'),
        ),
        migrations.AlterField(
            model_name='ictcomponent',
            name='component_type',
            field=models.CharField(choices=[('server', 'Server'), ('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('database', 'Database'), ('application', 'Business Application'), ('software', 'Software'), ('hardware', 'Hardware'), ('cloud', 'Cloud Service'), ('network', 'Network Equipment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog.category', verbose_name='Technical Categories'),
        ),
        migrations.AlterField(
            model_name='post',
            name='components',
            field=models.ManyToManyField(blank=True, to='blog.ictcomponent', verbose_name='Relevant ICT Components'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Describe the solution that resolved the issue', verbose_name='Applied Solution'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='post',
            name='problem_description',
            field=models.TextField(help_text='Describe the issue in detail', verbose_name='Problem Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Average Rating'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('resolved', 'Resolved')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(help_text='Brief summary of the issue and solution', max_length=500, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Article Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='useful_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Useful Count'),
        ),
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View Count'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(choices=[(1, '1 star(s)'), (2, '2 star(s)'), (3, '3 star(s)'), (4, '4 star(s)'), (5, '5 star(s)')]),
        ),
    ]
