# Generated by Django 5.2.7 on 2025-11-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_category_options_alter_ictcomponent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posthistory',
            name='new_content',
        ),
        migrations.RemoveField(
            model_name='posthistory',
            name='old_content',
        ),
        migrations.AddField(
            model_name='posthistory',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='posthistory',
            name='problem_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='posthistory',
            name='status',
            field=models.CharField(default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='posthistory',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='posthistory',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='change_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
