# Generated by Django 5.2.7 on 2025-10-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_ictcomponent_post_closure_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='problem_description',
            field=models.TextField(blank=True, default='', help_text='Problème rencontré'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, default='', help_text="Résumé court de l'article", max_length=300),
        ),
    ]
