# Generated by Django 5.2.7 on 2025-10-26 09:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_categories_alter_post_problem_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date'], 'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Article de connaissance', 'verbose_name_plural': 'Articles de connaissance'},
        ),
        migrations.AlterModelOptions(
            name='posthistory',
            options={'ordering': ['-modified_date'], 'verbose_name_plural': 'Historiques des articles'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='closure_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_solution',
            field=models.BooleanField(default=False, verbose_name='Marquer comme solution'),
        ),
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=20, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='post',
            name='useful_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre de 'utile'"),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='ictcomponent',
            name='component_type',
            field=models.CharField(choices=[('server', 'Serveur'), ('router', 'Routeur'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('database', 'Base de données'), ('application', 'Application métier'), ('software', 'Logiciel'), ('hardware', 'Matériel'), ('cloud', 'Service Cloud'), ('network', 'Équipement réseau')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ictcomponent',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog.category', verbose_name='Catégories techniques'),
        ),
        migrations.AlterField(
            model_name='post',
            name='components',
            field=models.ManyToManyField(blank=True, to='blog.ictcomponent', verbose_name='Composants ICT concernés'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Décrivez la solution qui a résolu le problème', verbose_name='Solution appliquée'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='post',
            name='problem_description',
            field=models.TextField(help_text='Décrivez le problème rencontré en détail', verbose_name='Description du problème'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Note moyenne'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé'), ('resolved', 'Résolu')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(help_text='Résumé court du problème et de la solution', max_length=500, verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name="Titre de l'article"),
        ),
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='posthistory',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(choices=[(1, '1 étoile(s)'), (2, '2 étoile(s)'), (3, '3 étoile(s)'), (4, '4 étoile(s)'), (5, '5 étoile(s)')]),
        ),
        migrations.CreateModel(
            name='UsefulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useful_votes', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote utile',
                'verbose_name_plural': 'Votes utiles',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
