# Generated by Django 5.2.7 on 2025-11-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='priority',
        ),
    ]
