# Generated by Django 5.2.7 on 2025-11-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictcomponent',
            name='component_type',
            field=models.CharField(choices=[('network', 'Network Device'), ('database', 'Database'), ('server', 'Server / Application')], default='server', max_length=20),
        ),
    ]
