# Generated by Django 5.2.7 on 2025-11-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_ictcomponent_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictcomponent',
            name='component_type',
            field=models.CharField(choices=[('server', 'Server'), ('erp', 'ERP System'), ('database', 'Database Server'), ('modem', 'Modem'), ('router', 'Router')], default='server', max_length=20),
        ),
    ]
