# Generated by Django 5.2.7 on 2025-11-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_posthistory_new_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictcomponent',
            name='component_type',
            field=models.CharField(choices=[('server', 'Server'), ('erp', 'ERP System'), ('database', 'Database Server'), ('modem', 'Modem'), ('router', 'Router'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
