# Generated by Django 5.2.7 on 2025-12-13 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_content_alter_post_problem_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('execution_time', models.TimeField()),
                ('export_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV')], max_length=10)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('component_id', models.IntegerField(blank=True, null=True)),
                ('author_username', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
