# Generated by Django 5.2.7 on 2025-12-14 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_scheduledexport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledexport',
            name='author_username',
        ),
        migrations.RemoveField(
            model_name='scheduledexport',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='scheduledexport',
            name='component_id',
        ),
        migrations.AddField(
            model_name='scheduledexport',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_exports_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledexport',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_exports', to='blog.category'),
        ),
        migrations.AddField(
            model_name='scheduledexport',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_exports', to='blog.ictcomponent'),
        ),
        migrations.AlterField(
            model_name='scheduledexport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_exports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduledexport',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], max_length=10),
        ),
    ]
