# Generated by Django 5.2.7 on 2025-12-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_scheduledexport_author_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledexport',
            name='category',
        ),
        migrations.RemoveField(
            model_name='scheduledexport',
            name='component',
        ),
        migrations.AddField(
            model_name='scheduledexport',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='scheduled_exports', to='blog.category'),
        ),
        migrations.AddField(
            model_name='scheduledexport',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='scheduled_exports', to='blog.ictcomponent'),
        ),
    ]
