# Generated by Django 5.2.7 on 2025-12-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_scheduledexport_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledExport',
        ),
    ]
